routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[\App\Http\Controllers\HomeController::class,'index'])->name('home');


Auth::routes();
Route::group(['prefix'=>'berita'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detail'])->name('detail');
});
Route::group(['prefix'=>'agenda'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detailAgenda'])->name('detailAgenda');
});

Route::group(['prefix'=>'detailBeritaFoto'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detailBeritaFoto'])->name('detailBeritaFoto');
});

Route::get('ppid',[\App\Http\Controllers\HomeController::class,'ppid'])->name('ppid');
Route::post('ppid/search',[\App\Http\Controllers\HomeController::class,'searchActionPPID'])->name('searchActionPPID');
Route::get('ppid/permohonan',[\App\Http\Controllers\HomeController::class,'ppidPermohonan'])->name('ppidPermohonan');
Route::post('ppid/permohonan',[\App\Http\Controllers\HomeController::class,'ppidPermohonanAction'])->name('ppidPermohonanAction');
Route::get('categori/berita/{slug}',[\App\Http\Controllers\HomeController::class,'categorySelect'])->name('categorySelect');


Route::get('more-new',[\App\Http\Controllers\HomeController::class,'moreNew'])->name('moreNew');
Route::post('search',[\App\Http\Controllers\HomeController::class,'searchAction'])->name('searchAction');
Route::get('search/{name}',[\App\Http\Controllers\HomeController::class,'search'])->name('search');
Route::get('profile',[\App\Http\Controllers\HomeController::class,'profile'])->name('profile');
Route::get('tupoksi',[\App\Http\Controllers\HomeController::class,'tupoksi'])->name('tupoksi');
Route::get('struktur',[\App\Http\Controllers\HomeController::class,'structure'])->name('structure');
Route::get('peraturan',[\App\Http\Controllers\HomeController::class,'regulations'])->name('regulations');
Route::get('peraturan/{id}',[\App\Http\Controllers\HomeController::class,'regulationsFilter'])->name('regulationsFilter');


Route::get('downloads',[\App\Http\Controllers\HomeController::class,'downloads'])->name('downloads');
Route::get('landing-pengaduan',[\App\Http\Controllers\HomeController::class,'landingPengaduan'])->name('landingPengaduan');
Route::get('pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduan'])->name('pengaduan');
Route::post('pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduanAction'])->name('pengaduanAction');
Route::post('cek/pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduanActionCek'])->name('pengaduanActionCek');
//Route::get('laporan',[\App\Http\Controllers\HomeController::class,'report'])->name('report');
Route::get('agenda/select/{date}',[\App\Http\Controllers\HomeController::class,'agendaSelectDate'])->name('agendaSelectDate');

Route::post('news/comment/{id}/{cek}',[\App\Http\Controllers\HomeController::class,'commentNew'])->name('commentNew');

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']],function (){

    Route::group(['as'=>'auth.'],function (){
        Route::get('dashboard',[\App\Http\Controllers\Admin\DashboardController::class,'index'])->name('dashboard');

        Route::get('log/clients',[\App\Http\Controllers\Admin\DashboardController::class,'logClients'])->name('logClients');

        Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
        Route::get('users/destroy/{id}',[\App\Http\Controllers\Admin\UserController::class,'destroy'])->name('usersDestroy');

        Route::resource('pengaduan', \App\Http\Controllers\Admin\PengaduanController::class);
        Route::get('pengaduan/destroy/{id}',[\App\Http\Controllers\Admin\PengaduanController::class,'destroy'])->name('pengaduanDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/destroy/{id}',[\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/destroy/{id}',[\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('news', \App\Http\Controllers\Admin\NewsController::class);
        Route::get('news/destroy/{id}',[\App\Http\Controllers\Admin\NewsController::class,'destroy'])->name('newsDestroy');

        Route::resource('newGalleries', \App\Http\Controllers\Admin\NewGalleriesController::class);
        Route::get('newGalleries/destroy/{id}',[\App\Http\Controllers\Admin\NewGalleriesController::class,'destroy'])->name('newGalleriesDestroy');
        Route::post('newGalleries/selectDelete', [\App\Http\Controllers\Admin\NewGalleriesController::class,'selectDelete'])->name('newGalleries.selectDelete');

        Route::resource('profile', \App\Http\Controllers\Admin\ProfileController::class);
        Route::get('profile/destroy/{id}',[\App\Http\Controllers\Admin\ProfileController::class,'destroy'])->name('profileDestroy');

        Route::resource('tupoksi', \App\Http\Controllers\Admin\TupoksiController::class);
        Route::get('tupoksi/destroy/{id}',[\App\Http\Controllers\Admin\TupoksiController::class,'destroy'])->name('tupoksiDestroy');

        Route::resource('structure', \App\Http\Controllers\Admin\StructureController::class);
        Route::get('structure/destroy/{id}',[\App\Http\Controllers\Admin\StructureController::class,'destroy'])->name('structureDestroy');

        Route::resource('regulations', \App\Http\Controllers\Admin\RegulationsController::class);
        Route::get('regulations/destroy/{id}',[\App\Http\Controllers\Admin\RegulationsController::class,'destroy'])->name('regulationsDestroy');
        Route::get('regulations/destroyStatus/{id}',[\App\Http\Controllers\Admin\RegulationsController::class,'status'])->name('regulationsDestroyStatus');

        Route::resource('levels', \App\Http\Controllers\Admin\LevelRegulationController::class);
        Route::get('levels/destroy/{id}',[\App\Http\Controllers\Admin\LevelRegulationController::class,'destroy'])->name('levelsDestroy');

        Route::resource('agenda', \App\Http\Controllers\Admin\AgendaController::class);
        Route::get('agenda/destroy/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'destroy'])->name('agendaDestroy');
        Route::get('agenda/selesaiView/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'selesai'])->name('agendaSelesaiView');
        Route::post('agenda/selesaiPost/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'selesaiPost'])->name('agendaSelesaiPost');

        Route::resource('carousel', \App\Http\Controllers\Admin\CarouselController::class);
        Route::get('carousel/destroy/{id}',[\App\Http\Controllers\Admin\CarouselController::class,'destroy'])->name('carouselDestroy');
        Route::get('carousel/active/{id}',[\App\Http\Controllers\Admin\CarouselController::class,'carouselActive'])->name('carouselActive');

        Route::resource('pariwara', \App\Http\Controllers\Admin\PariwaraController::class);
        Route::get('pariwara/destroy/{id}',[\App\Http\Controllers\Admin\PariwaraController::class,'destroy'])->name('pariwaraDestroy');

        Route::resource('relatedWebsites', \App\Http\Controllers\Admin\RelatedWebsitesController::class);
        Route::get('relatedWebsites/destroy/{id}',[\App\Http\Controllers\Admin\RelatedWebsitesController::class,'destroy'])->name('relatedWebsitesDestroy');

        Route::resource('report', \App\Http\Controllers\Admin\ReportController::class);
        Route::get('report/destroy/{id}',[\App\Http\Controllers\Admin\ReportController::class,'destroy'])->name('reportDestroy');

        Route::resource('complaint', \App\Http\Controllers\Admin\ComplaintController::class);
        Route::get('complaint/destroy/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'destroy'])->name('complaintDestroy');
        Route::get('complaint/tindaklanjut/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'tindaklanjut'])->name('complaintTindaklanjut');
        Route::get('complaint/selesai/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'selesai'])->name('complaintSelesai');

        Route::resource('ppid', \App\Http\Controllers\Admin\PpidController::class);
        Route::get('ppid/destroy/{id}',[\App\Http\Controllers\Admin\PpidController::class,'destroy'])->name('ppidDestroy');

        Route::resource('permohonan', \App\Http\Controllers\Admin\PermohonanController::class);
        Route::get('permohonan/destroy/{id}',[\App\Http\Controllers\Admin\PermohonanController::class,'destroy'])->name('permohonanDestroy');

        Route::resource('informationPPID', \App\Http\Controllers\Admin\InformationPPIDController::class);
        Route::get('informationPPID/destroy/{id}',[\App\Http\Controllers\Admin\InformationPPIDController::class,'destroy'])->name('informationPPIDDestroy');

        Route::resource('videoProfile', \App\Http\Controllers\Admin\VideoProfileController::class);
        Route::get('videoProfile/destroy/{id}',[\App\Http\Controllers\Admin\VideoProfileController::class,'destroy'])->name('videoProfileDestroy');
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

resources/views/landing/components/partials/footer.blade.php
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
@include('landing.components.style-footer')
<footer class="footer_area section_padding_130_0">
    <div class="container">
        <div class="row">
            <!-- Single Widget-->
            <div class="col-12 col-sm-6 col-lg-4">
                <div class="single-footer-widget section_padding_0_130">
                    <!-- Footer Logo-->
                    <div class="footer-logo mb-3"></div>
                    <p>Dinas Lingkungan Hidup - Propinsi Jawa Timur.</p>
                    <!-- Copywrite Text-->
                    <div class="copywrite-text mb-5">
                        <p class="mb-0">Made with <i class="lni-heart mr-1"></i>by<a class="ml-1" href="https://wrapbootstrap.com/user/DesigningWorld">twentrishcode</a></p>
                    </div>
                    <!-- Footer Social Area-->
                    <div class="footer_social_area"><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Facebook"><i class="fa fa-facebook"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Pinterest"><i class="fa fa-pinterest"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Skype"><i class="fa fa-skype"></i></a><a href="#" data-toggle="tooltip" data-placement="top" title="" data-original-title="Twitter"><i class="fa fa-twitter"></i></a></div>
                </div>
            </div>
            <!-- Single Widget-->
            <div class="col-12 col-sm-6 col-lg">
                <div class="single-footer-widget section_padding_0_130">
                    <!-- Widget Title-->
                    <h5 class="widget-title">About</h5>
                    <!-- Footer Menu-->
                    <div class="footer_menu">
                        <ul>
                            <li><a href="#">About Us</a></li>
                            <li><a href="#">Corporate Sale</a></li>
                            <li><a href="#">Terms &amp; Policy</a></li>
                            <li><a href="#">Community</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Single Widget-->
            <div class="col-12 col-sm-6 col-lg">
                <div class="single-footer-widget section_padding_0_130">
                    <!-- Widget Title-->
                    <h5 class="widget-title">Support</h5>
                    <!-- Footer Menu-->
                    <div class="footer_menu">
                        <ul>
                            <li><a href="#">Help</a></li>
                            <li><a href="#">Support</a></li>
                            <li><a href="#">Privacy Policy</a></li>
                            <li><a href="#">Term &amp; Conditions</a></li>
                            <li><a href="#">Help &amp; Support</a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!-- Single Widget-->
            <div class="col-12 col-sm-6 col-lg">
                <div class="single-footer-widget section_padding_0_130">
                    <!-- Widget Title-->
                    <h5 class="widget-title">Contact</h5>
                    <!-- Footer Menu-->
                    <div class="footer_menu">
                        <ul>
                            <li><a href="#">Call Centre</a></li>
                            <li><a href="#">Email Us</a></li>
                            <li><a href="#">Term &amp; Conditions</a></li>
                            <li><a href="#">Help Center</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/landing/components/partials/message.blade.php
@if ($message = Session::get('success'))
<div class="alert alert-success">
    <button type="button" class="close">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('danger'))
<div class="alert alert-danger alert-block">
    <button type="button" class="close">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('warning'))
<div class="alert alert-warning alert-block">
    <button type="button" class="close">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($message = Session::get('info'))
<div class="alert alert-info alert-block">
    <button type="button" class="close">×</button>
    <strong>{{ $message }}</strong>
</div>
@endif

@if ($errors->any())
<div class="alert alert-danger">
    <button type="button" class="close">×</button>
    Please check the form below for errors
</div>
@endif

resources/views/landing/components/partials/nav.blade.php
<nav class="navbar navbar-expand-md fixed-top navbar-dark padding-a" style="padding-right: 100px;padding-left: 100px;padding-top: 10px;padding-bottom: 10px">
    <a class="navbar-brand" href="#">
        <img src="{{asset('uploads/landing/dlh-logo-putih.png')}}" width="230" height="70" alt="">
    </a>
    <button style="background: #7ec37e" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon "></span>
    </button>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarCollapse">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active" style="margin-right: 10px">
                <a class="nav-link" href="{{route('home')}}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active" style="margin-right: 10px">
                <a class="nav-link" href="{{route('ppid')}}">PPID</a>
            </li>
            <li class="nav-item dropdown active" style="margin-right: 10px">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Profil
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{{route('profile')}}" style="font-weight: lighter">PROFILE</a>
                    <a class="dropdown-item" href="{{route('tupoksi')}}">TUPOKSI</a>
                    <a class="dropdown-item" href="{{route('structure')}}">STRUKTUR</a>
{{--                    <a class="dropdown-item" href="{{route('regulations')}}">PERATURAN/UU</a>--}}
                </div>
            </li>
            <li class="nav-item active" style="margin-right: 10px">
                <a class="nav-link" href="{{route('landingPengaduan')}}">E-Pengaduan <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown active" style="margin-right: 10px">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Publikasi data
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {{--                    <a class="dropdown-item" href="{{route('downloads')}}" style="font-weight: lighter">DOWNLOAD</a>--}}
                    <a class="dropdown-item" href="{{route('regulations')}}">Peraturan</a>
                    <a class="dropdown-item" href="{{route('downloads')}}">Laporan</a>
                </div>
            </li>
            <li class="nav-item dropdown active" style="margin-right: 10px">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    LAINNYA
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
{{--                    <a class="dropdown-item" href="{{route('downloads')}}" style="font-weight: lighter">DOWNLOAD</a>--}}
{{--                    <a class="dropdown-item" href="{{route('pengaduan')}}">PENGADUAN</a>--}}
{{--                    <a class="dropdown-item" href="#">E-IKPLHD</a>--}}
                    <a class="dropdown-item" href="#">E-SIMONIKA</a>
                    <a class="dropdown-item" href="#">UPT LAB</a>
                    <a class="dropdown-item" href="#">EKINERJA</a>
                </div>
            </li>
            <li class="nav-item">
                <label class="theme-switch" for="checkbox">
                    <input type="checkbox" id="checkbox"/>
                    <div class="slider round"></div>
                </label>
            </li>

        </ul>
    </div>

</nav>

resources/views/landing/components/partials/sidebar.blade.php
<div class="main-sidebar">
    <aside id="sidebar-wrapper">
        <div class="sidebar-brand">
                <a href="index.html">Dlh</a>
        </div>
        <div class="sidebar-brand sidebar-brand-sm">
            <a href="index.html">Dlh</a>
        </div>
        <ul class="sidebar-menu">
            <li class="menu-header">Dashboard</li>
            <li class="nav-item dropdown active">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Dashboard</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="index-0.html">General Dashboard</a></li>
                    <li class="active"><a class="nav-link" href="index.html">Ecommerce Dashboard</a></li>
                </ul>
            </li>

            <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>Master</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{route('admin.auth.categories.index')}}">Categories</a></li>
                    <li><a class="nav-link" href="{{route('admin.auth.news.index')}}">News</a></li>
                    <li><a class="nav-link" href="{{route('admin.auth.newGalleries.index')}}">New Galleries</a></li>
                    <li><a class="nav-link" href="{{route('admin.auth.agenda.index')}}">Agenda</a></li>

                </ul>
            </li>

            <li class="nav-item dropdown">
                <a href="#" class="nav-link has-dropdown"><i class="fas fa-fire"></i><span>About Us</span></a>
                <ul class="dropdown-menu">
                    <li><a class="nav-link" href="{{route('admin.auth.profile.index')}}">Profile</a></li>
                    <li><a class="nav-link" href="{{route('admin.auth.tupoksi.index')}}">Tupoksi</a></li>
                    <li><a class="nav-link" href="{{route('admin.auth.structure.index')}}">Structure</a></li>
                    <li><a class="nav-link" href="{{route('admin.auth.regulations.index')}}">Regulations/UU</a></li>

                </ul>
            </li>
            <li><a class="nav-link" href="credits.html"><i class="fas fa-pencil-ruler"></i> <span>Credits</span></a></li>
        </ul>

        <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
            <a href="https://getstisla.com/docs" class="btn btn-primary btn-lg btn-block btn-icon-split">
                <i class="fas fa-rocket"></i> Documentation
            </a>
        </div>
    </aside>
</div>