routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[\App\Http\Controllers\HomeController::class,'index'])->name('home');


Auth::routes();
Route::group(['prefix'=>'berita'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detail'])->name('detail');
});
Route::group(['prefix'=>'agenda'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detailAgenda'])->name('detailAgenda');
});

Route::group(['prefix'=>'detailBeritaFoto'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detailBeritaFoto'])->name('detailBeritaFoto');
});

Route::get('ppid',[\App\Http\Controllers\HomeController::class,'ppid'])->name('ppid');
Route::post('ppid/search',[\App\Http\Controllers\HomeController::class,'searchActionPPID'])->name('searchActionPPID');
Route::get('ppid/permohonan',[\App\Http\Controllers\HomeController::class,'ppidPermohonan'])->name('ppidPermohonan');
Route::post('ppid/permohonan',[\App\Http\Controllers\HomeController::class,'ppidPermohonanAction'])->name('ppidPermohonanAction');
Route::get('categori/berita/{slug}',[\App\Http\Controllers\HomeController::class,'categorySelect'])->name('categorySelect');


Route::get('more-new',[\App\Http\Controllers\HomeController::class,'moreNew'])->name('moreNew');
Route::post('search',[\App\Http\Controllers\HomeController::class,'searchAction'])->name('searchAction');
Route::get('search/{name}',[\App\Http\Controllers\HomeController::class,'search'])->name('search');
Route::get('profile',[\App\Http\Controllers\HomeController::class,'profile'])->name('profile');
Route::get('tupoksi',[\App\Http\Controllers\HomeController::class,'tupoksi'])->name('tupoksi');
Route::get('struktur',[\App\Http\Controllers\HomeController::class,'structure'])->name('structure');
Route::get('peraturan',[\App\Http\Controllers\HomeController::class,'regulations'])->name('regulations');
Route::get('peraturan/{id}',[\App\Http\Controllers\HomeController::class,'regulationsFilter'])->name('regulationsFilter');


Route::get('downloads',[\App\Http\Controllers\HomeController::class,'downloads'])->name('downloads');
Route::get('landing-pengaduan',[\App\Http\Controllers\HomeController::class,'landingPengaduan'])->name('landingPengaduan');
Route::get('pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduan'])->name('pengaduan');
Route::post('pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduanAction'])->name('pengaduanAction');
Route::post('cek/pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduanActionCek'])->name('pengaduanActionCek');
//Route::get('laporan',[\App\Http\Controllers\HomeController::class,'report'])->name('report');
Route::get('agenda/select/{date}',[\App\Http\Controllers\HomeController::class,'agendaSelectDate'])->name('agendaSelectDate');

Route::post('news/comment/{id}/{cek}',[\App\Http\Controllers\HomeController::class,'commentNew'])->name('commentNew');

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']],function (){

    Route::group(['as'=>'auth.'],function (){
        Route::get('dashboard',[\App\Http\Controllers\Admin\DashboardController::class,'index'])->name('dashboard');

        Route::get('log/clients',[\App\Http\Controllers\Admin\DashboardController::class,'logClients'])->name('logClients');

        Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
        Route::get('users/destroy/{id}',[\App\Http\Controllers\Admin\UserController::class,'destroy'])->name('usersDestroy');

        Route::resource('pengaduan', \App\Http\Controllers\Admin\PengaduanController::class);
        Route::get('pengaduan/destroy/{id}',[\App\Http\Controllers\Admin\PengaduanController::class,'destroy'])->name('pengaduanDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/destroy/{id}',[\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/destroy/{id}',[\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('news', \App\Http\Controllers\Admin\NewsController::class);
        Route::get('news/destroy/{id}',[\App\Http\Controllers\Admin\NewsController::class,'destroy'])->name('newsDestroy');

        Route::resource('newGalleries', \App\Http\Controllers\Admin\NewGalleriesController::class);
        Route::get('newGalleries/destroy/{id}',[\App\Http\Controllers\Admin\NewGalleriesController::class,'destroy'])->name('newGalleriesDestroy');
        Route::post('newGalleries/selectDelete', [\App\Http\Controllers\Admin\NewGalleriesController::class,'selectDelete'])->name('newGalleries.selectDelete');

        Route::resource('profile', \App\Http\Controllers\Admin\ProfileController::class);
        Route::get('profile/destroy/{id}',[\App\Http\Controllers\Admin\ProfileController::class,'destroy'])->name('profileDestroy');

        Route::resource('tupoksi', \App\Http\Controllers\Admin\TupoksiController::class);
        Route::get('tupoksi/destroy/{id}',[\App\Http\Controllers\Admin\TupoksiController::class,'destroy'])->name('tupoksiDestroy');

        Route::resource('structure', \App\Http\Controllers\Admin\StructureController::class);
        Route::get('structure/destroy/{id}',[\App\Http\Controllers\Admin\StructureController::class,'destroy'])->name('structureDestroy');

        Route::resource('regulations', \App\Http\Controllers\Admin\RegulationsController::class);
        Route::get('regulations/destroy/{id}',[\App\Http\Controllers\Admin\RegulationsController::class,'destroy'])->name('regulationsDestroy');
        Route::get('regulations/destroyStatus/{id}',[\App\Http\Controllers\Admin\RegulationsController::class,'status'])->name('regulationsDestroyStatus');

        Route::resource('levels', \App\Http\Controllers\Admin\LevelRegulationController::class);
        Route::get('levels/destroy/{id}',[\App\Http\Controllers\Admin\LevelRegulationController::class,'destroy'])->name('levelsDestroy');

        Route::resource('agenda', \App\Http\Controllers\Admin\AgendaController::class);
        Route::get('agenda/destroy/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'destroy'])->name('agendaDestroy');
        Route::get('agenda/selesaiView/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'selesai'])->name('agendaSelesaiView');
        Route::post('agenda/selesaiPost/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'selesaiPost'])->name('agendaSelesaiPost');

        Route::resource('carousel', \App\Http\Controllers\Admin\CarouselController::class);
        Route::get('carousel/destroy/{id}',[\App\Http\Controllers\Admin\CarouselController::class,'destroy'])->name('carouselDestroy');
        Route::get('carousel/active/{id}',[\App\Http\Controllers\Admin\CarouselController::class,'carouselActive'])->name('carouselActive');

        Route::resource('pariwara', \App\Http\Controllers\Admin\PariwaraController::class);
        Route::get('pariwara/destroy/{id}',[\App\Http\Controllers\Admin\PariwaraController::class,'destroy'])->name('pariwaraDestroy');

        Route::resource('relatedWebsites', \App\Http\Controllers\Admin\RelatedWebsitesController::class);
        Route::get('relatedWebsites/destroy/{id}',[\App\Http\Controllers\Admin\RelatedWebsitesController::class,'destroy'])->name('relatedWebsitesDestroy');

        Route::resource('report', \App\Http\Controllers\Admin\ReportController::class);
        Route::get('report/destroy/{id}',[\App\Http\Controllers\Admin\ReportController::class,'destroy'])->name('reportDestroy');

        Route::resource('complaint', \App\Http\Controllers\Admin\ComplaintController::class);
        Route::get('complaint/destroy/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'destroy'])->name('complaintDestroy');
        Route::get('complaint/tindaklanjut/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'tindaklanjut'])->name('complaintTindaklanjut');
        Route::get('complaint/selesai/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'selesai'])->name('complaintSelesai');

        Route::resource('ppid', \App\Http\Controllers\Admin\PpidController::class);
        Route::get('ppid/destroy/{id}',[\App\Http\Controllers\Admin\PpidController::class,'destroy'])->name('ppidDestroy');

        Route::resource('permohonan', \App\Http\Controllers\Admin\PermohonanController::class);
        Route::get('permohonan/destroy/{id}',[\App\Http\Controllers\Admin\PermohonanController::class,'destroy'])->name('permohonanDestroy');

        Route::resource('informationPPID', \App\Http\Controllers\Admin\InformationPPIDController::class);
        Route::get('informationPPID/destroy/{id}',[\App\Http\Controllers\Admin\InformationPPIDController::class,'destroy'])->name('informationPPIDDestroy');

        Route::resource('videoProfile', \App\Http\Controllers\Admin\VideoProfileController::class);
        Route::get('videoProfile/destroy/{id}',[\App\Http\Controllers\Admin\VideoProfileController::class,'destroy'])->name('videoProfileDestroy');
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Agenda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Agenda extends Model
{
    use HasFactory;

    public function user(){
        return $this->belongsTo(User::class,'user_id');
    }
}

app/Http/Controllers/Admin/AgendaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Agenda;
use App\Models\Category;
use App\Models\News;
use App\Models\Regulation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Yajra\DataTables\DataTables;

class AgendaController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $data = Agenda::all();
            return DataTables::of($data)
                ->addColumn('user', function($data){
                    $a = $data->user->name;
                    return $a;
                })
                ->addColumn('desc', function($data){
                    $a = \Str::limit($data->desc_banner, 100, $end='......');
                    return $a;
                })->addColumn('active_flag', function($data){
                    if ($data->active_flag == '1'){
                        $a = '<div class="badge badge-success">Active</div>';
                    }else{
                        $a = '<div class="badge badge-danger">non-Active</div>';

                    }
                    return $a;
                })
                ->addColumn('action', function($data){
                    $button = '<a href="agenda/'.$data->id.'/edit'.'" class="btn btn-info"><i class="fa fa-pencil"></i> Edit</a>';
                    $button .= '<a href="'.route('admin.auth.agendaSelesaiView',$data->id).'" class="btn btn-warning">Selesai</a>';
                    $button .= '<a  href="'.route('admin.auth.agendaDestroy',$data->id).'" class="btn btn-danger" onclick="return confirm('.'`Are you sure?`'.')"><i class="fa fa-trash"></i> Delete</a>';
                    return $button;
                })
                ->rawColumns(['desc','user','active_flag','action'])
                ->make(true);
        }
        return view('admin.content.agenda.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;

        view()->share([
            'data' => $data
        ]);
        return view('admin.content.agenda.form');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validates = [
            'name' => 'required|unique:agendas,name',
            'desc' => 'required',
            'location' => 'required',
            'date_start' => 'required',
            'date_end' => 'required',
            'time' => 'required',
            'image' => 'required|mimes:jpeg,png,jpg,svg'
        ];

        $request->validate($validates);

        $data = new Agenda();


        if ($request->file('image')){
            $file = $request->file('image');
            $name = rand(999999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
            $imgDB = 'uploads/agenda/'.$newName;

            $request->image->move(public_path('uploads/agenda/'), $newName);
            $data->img = $imgDB;
        }else{
            $data->img = $data->img ;
        }

        $data->user_id = Auth::user()->id;
        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->desc = $request->desc;
        $data->location = $request->location;
        $data->date_start = $request->date_start;
        $data->date_end = $request->date_end;
        $data->time = $request->time;
        $data->desc_banner = strip_tags($request->desc);

        $data->save();

        return redirect()->route('admin.auth.agenda.index')->withSuccess('Succcess create data');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Agenda::find($id);

        view()->share([
            'data' => $data
        ]);
        return view('admin.content.agenda.form');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validates = [
            'desc' => 'required',
            'location' => 'required',
            'date_start' => 'required',
            'date_end' => 'required',
            'time' => 'required',
        ];

        $request->validate($validates);

        $data = Agenda::find($id);


        if ($request->file('image')){
            $file = $request->file('image');
            $name = rand(999999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
            $imgDB = 'uploads/agenda/'.$newName;

            $request->image->move(public_path('uploads/agenda/'), $newName);
            $data->img = $imgDB;
        }else{
            $data->img = $data->img ;
        }

        $data->user_id = Auth::user()->id;
        $data->name = $request->name;
        $data->slug = \Str::slug($request->name);
        $data->desc = $request->desc;
        $data->location = $request->location;
        $data->date_start = $request->date_start;
        $data->date_end = $request->date_end;
        $data->time = $request->time;
        $data->desc_banner = strip_tags($request->desc);
        $data->save();

        return redirect()->route('admin.auth.agenda.index')->withSuccess('Succcess update data');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Agenda::find($id);


        $data->active_flag = '0';
        $data->save();
        return redirect()->route('admin.auth.agenda.index')->withDanger('Succcess non-active data');

    }

    public function selesai($id)
    {
        $data = Agenda::find($id);

        view()->share([
            'data' => $data
        ]);
        return view('admin.content.agenda.selesai');

    }
    public function selesaiPost($id,Request $request)
    {
        $validates = [
            'file' => 'required|mimes:pdf,doc,docx',
        ];

        $request->validate($validates);

        $data = Agenda::find($id);

        $data->status = 'sudah berlangsung' ;

        if ($request->file('file')){
            $file = $request->file('file');
            $name = rand(999999999,1);
            $extension = $file->getClientOriginalExtension();
            $newName = $name.'.'.$extension;
            $imgDB = 'uploads/regulation/'.$request->level_id.'/'.$newName;

            $request->file->move(public_path('uploads/regulation/'.$request->level_id.'/'), $newName);
            $data->file = $imgDB;
        }else{
            $data->file = $data->file ;
        }

        $data->save();

        return redirect()->route('admin.auth.agenda.index')->withSuccess('Agenda sudah selesai');

    }
}

resources/views/admin/content/agenda/form.blade.php
@extends('admin.app')

@section('content')


<div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Form Agenda</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{($data!=null) ? route('admin.auth.agenda.update',$data->id) : route('admin.auth.agenda.store')}}" method="post" enctype="multipart/form-data">
                                    @csrf

                                    @if($data!=null)
                                        @method('put')
                                    @endif

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Name</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{($data!=null) ? $data->name : ''}}">
                                            @error('name')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="file" name="image" id="image">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Desc</label>
                                        <div class="col-sm-12 col-md-7">
                                            <textarea id="summernote" name="desc">{!! ($data!=null) ? $data->desc : '' !!}</textarea>
                                            @error('desc')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Location</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="location" id="location" class="form-control @error('location') is-invalid @enderror" value="{{($data!=null) ? $data->location : ''}}">
                                            @error('location')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Date Start </label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="date" name="date_start" id="date_start" class="form-control @error('date_start') is-invalid @enderror" value="{{($data!=null) ? date('Y-m-d', strtotime($data->date_start)) :''}}">
                                            @error('date_start')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">End Start</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="date" name="date_end" id="date_end" class="form-control @error('date_end') is-invalid @enderror" value="{{($data!=null) ? date('Y-m-d', strtotime($data->date_end)) :''}}">
                                            @error('date_end')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Time</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="time" name="time" class="form-control @error('time') is-invalid @enderror" value="{{($data!=null) ? $data->time : ''}}">
                                            @error('time')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote();
        });

    </script>
@endsection

resources/views/admin/content/agenda/index.blade.php
@extends('admin.app')

@section('content')


    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Master</h1>
            </div>

            <div class="section-body">
                <h2 class="section-title">Agenda</h2>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                <a href="{{route('admin.auth.agenda.create')}}" class="btn btn-success text-white">create</a>

                                <br><br>
                                @include('admin.components.partials.message')
                                    <div class="table-responsive">
                                        <table class="table table-striped" id="item">
                                            <thead>
                                            <tr>
                                                <th>User</th>
                                                <th>Name</th>
                                                <th>Desc</th>
                                                <th>Img</th>
                                                <th>Location</th>
                                                <th>Start Date</th>
                                                <th>End Date</th>
                                                <th>Time</th>
                                                <th>Berjalan</th>
                                                <th>Status</th>
                                                <th>Action</th>
                                            </tr>
                                            </thead>

                                        </table>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    @push('script')
        <script type="text/javascript">
            $(document).ready(function(){
                $('#item').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: "{{route('admin.auth.agenda.index')}}",
                    },
                    columns: [
                        {
                            data: 'user',
                            name: 'user'
                        },
                        {
                            data: 'name',
                            name: 'name'
                        },
                        {
                            data: 'desc',
                            name: 'desc'
                        },
                        {
                            data: 'img',
                            name: 'img'
                        },
                        {
                            data: 'location',
                            name: 'location'
                        },
                        {
                            data: 'date_start',
                            name: 'date_start'
                        },
                        {
                            data: 'date_end',
                            name: 'date_end'
                        },
                        {
                            data: 'time',
                            name: 'time'
                        },
                        {
                            data: 'status',
                            name: 'status'
                        },
                        {
                            data: 'active_flag',
                            name: 'active_flag'
                        },
                        {
                            data: 'action',
                            name: 'action',
                            orderable: false
                        },

                    ]
                });
            });
        </script>

    @endpush
@endsection

resources/views/admin/content/agenda/selesai.blade.php
@extends('admin.app')

@section('content')


<div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Form Agenda</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{route('admin.auth.agendaSelesaiPost',$data->id)}}" method="post" enctype="multipart/form-data">
                                    @csrf


                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="file" name="file" id="image">
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote();
        });

    </script>
@endsection