routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/',[\App\Http\Controllers\HomeController::class,'index'])->name('home');


Auth::routes();
Route::group(['prefix'=>'berita'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detail'])->name('detail');
});
Route::group(['prefix'=>'agenda'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detailAgenda'])->name('detailAgenda');
});

Route::group(['prefix'=>'detailBeritaFoto'],function () {
    Route::get('{slug}',[\App\Http\Controllers\HomeController::class,'detailBeritaFoto'])->name('detailBeritaFoto');
});

Route::get('ppid',[\App\Http\Controllers\HomeController::class,'ppid'])->name('ppid');
Route::post('ppid/search',[\App\Http\Controllers\HomeController::class,'searchActionPPID'])->name('searchActionPPID');
Route::get('ppid/permohonan',[\App\Http\Controllers\HomeController::class,'ppidPermohonan'])->name('ppidPermohonan');
Route::post('ppid/permohonan',[\App\Http\Controllers\HomeController::class,'ppidPermohonanAction'])->name('ppidPermohonanAction');
Route::get('categori/berita/{slug}',[\App\Http\Controllers\HomeController::class,'categorySelect'])->name('categorySelect');


Route::get('more-new',[\App\Http\Controllers\HomeController::class,'moreNew'])->name('moreNew');
Route::post('search',[\App\Http\Controllers\HomeController::class,'searchAction'])->name('searchAction');
Route::get('search/{name}',[\App\Http\Controllers\HomeController::class,'search'])->name('search');
Route::get('profile',[\App\Http\Controllers\HomeController::class,'profile'])->name('profile');
Route::get('tupoksi',[\App\Http\Controllers\HomeController::class,'tupoksi'])->name('tupoksi');
Route::get('struktur',[\App\Http\Controllers\HomeController::class,'structure'])->name('structure');
Route::get('peraturan',[\App\Http\Controllers\HomeController::class,'regulations'])->name('regulations');
Route::get('peraturan/{id}',[\App\Http\Controllers\HomeController::class,'regulationsFilter'])->name('regulationsFilter');


Route::get('downloads',[\App\Http\Controllers\HomeController::class,'downloads'])->name('downloads');
Route::get('landing-pengaduan',[\App\Http\Controllers\HomeController::class,'landingPengaduan'])->name('landingPengaduan');
Route::get('pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduan'])->name('pengaduan');
Route::post('pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduanAction'])->name('pengaduanAction');
Route::post('cek/pengaduan',[\App\Http\Controllers\HomeController::class,'pengaduanActionCek'])->name('pengaduanActionCek');
//Route::get('laporan',[\App\Http\Controllers\HomeController::class,'report'])->name('report');
Route::get('agenda/select/{date}',[\App\Http\Controllers\HomeController::class,'agendaSelectDate'])->name('agendaSelectDate');

Route::post('news/comment/{id}/{cek}',[\App\Http\Controllers\HomeController::class,'commentNew'])->name('commentNew');

Route::group(['prefix'=>'admin','as'=>'admin.','middleware'=>['auth']],function (){

    Route::group(['as'=>'auth.'],function (){
        Route::get('dashboard',[\App\Http\Controllers\Admin\DashboardController::class,'index'])->name('dashboard');

        Route::get('log/clients',[\App\Http\Controllers\Admin\DashboardController::class,'logClients'])->name('logClients');

        Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
        Route::get('users/destroy/{id}',[\App\Http\Controllers\Admin\UserController::class,'destroy'])->name('usersDestroy');

        Route::resource('pengaduan', \App\Http\Controllers\Admin\PengaduanController::class);
        Route::get('pengaduan/destroy/{id}',[\App\Http\Controllers\Admin\PengaduanController::class,'destroy'])->name('pengaduanDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/destroy/{id}',[\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('categories', \App\Http\Controllers\Admin\CategoryController::class);
        Route::get('categories/destroy/{id}',[\App\Http\Controllers\Admin\CategoryController::class,'destroy'])->name('categoriesDestroy');

        Route::resource('news', \App\Http\Controllers\Admin\NewsController::class);
        Route::get('news/destroy/{id}',[\App\Http\Controllers\Admin\NewsController::class,'destroy'])->name('newsDestroy');

        Route::resource('newGalleries', \App\Http\Controllers\Admin\NewGalleriesController::class);
        Route::get('newGalleries/destroy/{id}',[\App\Http\Controllers\Admin\NewGalleriesController::class,'destroy'])->name('newGalleriesDestroy');
        Route::post('newGalleries/selectDelete', [\App\Http\Controllers\Admin\NewGalleriesController::class,'selectDelete'])->name('newGalleries.selectDelete');

        Route::resource('profile', \App\Http\Controllers\Admin\ProfileController::class);
        Route::get('profile/destroy/{id}',[\App\Http\Controllers\Admin\ProfileController::class,'destroy'])->name('profileDestroy');

        Route::resource('tupoksi', \App\Http\Controllers\Admin\TupoksiController::class);
        Route::get('tupoksi/destroy/{id}',[\App\Http\Controllers\Admin\TupoksiController::class,'destroy'])->name('tupoksiDestroy');

        Route::resource('structure', \App\Http\Controllers\Admin\StructureController::class);
        Route::get('structure/destroy/{id}',[\App\Http\Controllers\Admin\StructureController::class,'destroy'])->name('structureDestroy');

        Route::resource('regulations', \App\Http\Controllers\Admin\RegulationsController::class);
        Route::get('regulations/destroy/{id}',[\App\Http\Controllers\Admin\RegulationsController::class,'destroy'])->name('regulationsDestroy');
        Route::get('regulations/destroyStatus/{id}',[\App\Http\Controllers\Admin\RegulationsController::class,'status'])->name('regulationsDestroyStatus');

        Route::resource('levels', \App\Http\Controllers\Admin\LevelRegulationController::class);
        Route::get('levels/destroy/{id}',[\App\Http\Controllers\Admin\LevelRegulationController::class,'destroy'])->name('levelsDestroy');

        Route::resource('agenda', \App\Http\Controllers\Admin\AgendaController::class);
        Route::get('agenda/destroy/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'destroy'])->name('agendaDestroy');
        Route::get('agenda/selesaiView/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'selesai'])->name('agendaSelesaiView');
        Route::post('agenda/selesaiPost/{id}',[\App\Http\Controllers\Admin\AgendaController::class,'selesaiPost'])->name('agendaSelesaiPost');

        Route::resource('carousel', \App\Http\Controllers\Admin\CarouselController::class);
        Route::get('carousel/destroy/{id}',[\App\Http\Controllers\Admin\CarouselController::class,'destroy'])->name('carouselDestroy');
        Route::get('carousel/active/{id}',[\App\Http\Controllers\Admin\CarouselController::class,'carouselActive'])->name('carouselActive');

        Route::resource('pariwara', \App\Http\Controllers\Admin\PariwaraController::class);
        Route::get('pariwara/destroy/{id}',[\App\Http\Controllers\Admin\PariwaraController::class,'destroy'])->name('pariwaraDestroy');

        Route::resource('relatedWebsites', \App\Http\Controllers\Admin\RelatedWebsitesController::class);
        Route::get('relatedWebsites/destroy/{id}',[\App\Http\Controllers\Admin\RelatedWebsitesController::class,'destroy'])->name('relatedWebsitesDestroy');

        Route::resource('report', \App\Http\Controllers\Admin\ReportController::class);
        Route::get('report/destroy/{id}',[\App\Http\Controllers\Admin\ReportController::class,'destroy'])->name('reportDestroy');

        Route::resource('complaint', \App\Http\Controllers\Admin\ComplaintController::class);
        Route::get('complaint/destroy/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'destroy'])->name('complaintDestroy');
        Route::get('complaint/tindaklanjut/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'tindaklanjut'])->name('complaintTindaklanjut');
        Route::get('complaint/selesai/{id}',[\App\Http\Controllers\Admin\ComplaintController::class,'selesai'])->name('complaintSelesai');

        Route::resource('ppid', \App\Http\Controllers\Admin\PpidController::class);
        Route::get('ppid/destroy/{id}',[\App\Http\Controllers\Admin\PpidController::class,'destroy'])->name('ppidDestroy');

        Route::resource('permohonan', \App\Http\Controllers\Admin\PermohonanController::class);
        Route::get('permohonan/destroy/{id}',[\App\Http\Controllers\Admin\PermohonanController::class,'destroy'])->name('permohonanDestroy');

        Route::resource('informationPPID', \App\Http\Controllers\Admin\InformationPPIDController::class);
        Route::get('informationPPID/destroy/{id}',[\App\Http\Controllers\Admin\InformationPPIDController::class,'destroy'])->name('informationPPIDDestroy');

        Route::resource('videoProfile', \App\Http\Controllers\Admin\VideoProfileController::class);
        Route::get('videoProfile/destroy/{id}',[\App\Http\Controllers\Admin\VideoProfileController::class,'destroy'])->name('videoProfileDestroy');
    });
});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/Admin/PermohonanController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Complaint;
use App\Models\PermohonanPPID;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;

class PermohonanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if($request->ajax()) {
            $data = PermohonanPPID::orderBy('created_at','DESC')->get();
            return DataTables::of($data)
                ->addColumn('client_date_of_birth', function($data){
                    $a = Carbon::parse($data->client_date_of_birth)->toFormattedDateString();
                    return $a;
                })
                ->rawColumns(['client_date_of_birth'])
                ->make(true);
        }
        return view('admin.content.permohonan.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/content/permohonan/form.blade.php
@extends('admin.app')

@section('content')


<div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Form Agenda</h1>
            </div>
            <div class="section-body">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <form action="{{($data!=null) ? route('admin.auth.agenda.update',$data->id) : route('admin.auth.agenda.store')}}" method="post" enctype="multipart/form-data">
                                    @csrf

                                    @if($data!=null)
                                        @method('put')
                                    @endif

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Name</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{($data!=null) ? $data->name : ''}}">
                                            @error('name')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Image</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="file" name="image" id="image">
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Desc</label>
                                        <div class="col-sm-12 col-md-7">
                                            <textarea id="summernote" name="desc">{!! ($data!=null) ? $data->desc : '' !!}</textarea>
                                            @error('desc')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Location</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="text" name="location" id="location" class="form-control @error('location') is-invalid @enderror" value="{{($data!=null) ? $data->location : ''}}">
                                            @error('location')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Date Start </label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="date" name="date_start" id="date_start" class="form-control @error('date_start') is-invalid @enderror" value="{{($data!=null) ? date('Y-m-d', strtotime($data->date_start)) :''}}">
                                            @error('date_start')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">End Start</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="date" name="date_end" id="date_end" class="form-control @error('date_end') is-invalid @enderror" value="{{($data!=null) ? date('Y-m-d', strtotime($data->date_end)) :''}}">
                                            @error('date_end')
                                                <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Time</label>
                                        <div class="col-sm-12 col-md-7">
                                            <input type="time" name="time" class="form-control @error('time') is-invalid @enderror" value="{{($data!=null) ? $data->time : ''}}">
                                            @error('time')
                                            <div class="alert alert-danger">{{ $message }}</div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row mb-4">
                                        <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                        <div class="col-sm-12 col-md-7">
                                            <button class="btn btn-primary">save</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script>
        $(document).ready(function() {
            $('#summernote').summernote();
        });

    </script>
@endsection

resources/views/admin/content/permohonan/index.blade.php
@extends('admin.app')

@section('content')


    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Dashboard</h1>
            </div>
            <div class="section-body">
                <h2 class="section-title">Pengaduan</h2>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

                                {{--                                <a href="{{route('admin.auth.agenda.create')}}" class="btn btn-success text-white">create</a>--}}

                                <br><br>
                                @include('admin.components.partials.message')
                                <div class="table-responsive">
                                    <table class="table table-striped" id="item">
                                        <thead>
                                        <tr>
                                            <th>Name</th>
                                            <th>Email</th>
                                            <th>Telepon</th>
                                            <th>Tanggal Lahir</th>
                                            <th>Informasi Detail</th>
                                            <th>Tujuan Informasi</th>
                                            <th>Cara Memperoleh Informasi</th>
                                            <th>Cara Mendapatkan Salinan Informasi</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    @push('script')
        <script type="text/javascript">
            $(document).ready(function(){
                $('#item').DataTable({
                    processing: true,
                    serverSide: true,
                    ajax: {
                        url: "{{route('admin.auth.permohonan.index')}}",
                    },
                    columns: [
                        {
                            data: 'client_name',
                            name: 'client_name'
                        },
                        {
                            data: 'client_email',
                            name: 'client_email'
                        },
                        {
                            data: 'client_phone',
                            name: 'client_phone'
                        },
                        {
                            data: 'client_date_of_birth',
                            name: 'client_date_of_birth'
                        },
                        {
                            data: 'client_detail_information',
                            name: 'client_detail_information'
                        },
                        {
                            data: 'client_target_information',
                            name: 'client_target_information'
                        },
                        {
                            data: 'client_memperoleh',
                            name: 'client_memperoleh'
                        },
                        {
                            data: 'client_mendapatkan',
                            name: 'client_mendapatkan'
                        },

                    ]
                });
            });
        </script>

    @endpush
@endsection

resources/views/admin/content/permohonan/show.blade.php
@extends('admin.app')

@section('content')


    <!-- Main Content -->
    <div class="main-content">
        <section class="section">
            <div class="section-header">
                <h1>Dashboard</h1>
            </div>
            <div class="section-body">
                <h2 class="section-title">Show Pengaduan</h2>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">

{{--                                <a href="{{route('admin.auth.agenda.create')}}" class="btn btn-success text-white">create</a>--}}
                                @include('admin.components.partials.message')

                                <br><br>
                                <table class="table-responsive">
                                    <tr>
                                        <td> <h4>Nama Pengadu </h4></td>
                                        <td> <h4> : {{$data->client_name}}</h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>Email Pengadu </h4></td>
                                        <td> <h4> : {{$data->client_email}}</h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>Tanggal lahir Pengadu </h4></td>
                                        <td> <h4> : {{$data->client_date_of_birth}}</h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>Jenis Kelamin Pengadu </h4></td>
                                        <td> <h4> : {{$data->client_gender}}</h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>Lokasi Pengadu </h4></td>
                                        <td> <h4> : {{$data->client_location}}</h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>Alasan Mengadu </h4></td>
                                        <td> <h4> : {{$data->client_reason}}</h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>Dampak yang Dirasakan Pengadu </h4></td>
                                        <td> <h4> : {{$data->client_impact}}</h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>Pengaduan</h4></td>
                                        <td> <h4> : {{$data->client_complaint}}</h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>Status</h4></td>
                                        <td>
                                            @if($data->status == 0)
                                                <h4 class="text-danger"> : Belum Di tindak</h4>
                                            @elseif($data->status == 1)

                                                <h4 class="text-info"> : Sedang Di Tindak</h4>
                                            @else
                                                <h4 class="text-success"> : Selesai</h4>

                                            @endif
                                        </td>

                                    </tr>
                                    <tr>
                                        <td> <h4>File Pendukung</h4></td>
                                        <td> <h4> : <a href="{{asset($data->client_file)}}" class="btn btn-success">Lihat</a></h4></td>

                                    </tr>
                                    <tr>
                                        <td> <h4>KTP</h4></td>
                                        <td>
                                            <h4> : <a href="{{asset($data->ktp)}}" class="btn btn-success">Lihat</a></h4>
                                        </td>

                                    </tr>
                                </table>

                                @if($data->status == 0)
                                    <a href="{{route('admin.auth.complaintTindaklanjut',$data->id)}}" class="btn btn-info float-right" style="text-decoration: none;color: white">Tindak Lanjut</a>

                                @else
                                    <a href="{{route('admin.auth.complaintSelesai',$data->id)}}" class="btn btn-info float-right" style="text-decoration: none;color: white">Selesai</a>

                                @endif


                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection